[package]
name = "yasws"
version = "0.0.1"
authors = ["Remfath Chan <remfath@gmail.com>"]
edition = "2018"
license = "MIT"
description = "yet another simple web server written by rust"

[dependencies]